segments:
  - type: directory
    properties:
      max_depth: 3
      truncate: true
    style:
      foreground: "blue"
      bold: true

  - type: git
    properties:
      show_status: true
    style:
      foreground: "green"

  - type: language
    properties:
      show_version: false
    style:
      foreground: "yellow"

  - type: exit_code
    properties:
      show_always: false
    style:
      foreground: "red"

colors:
  primary: "#00FF00"
  secondary: "#0000FF"
  error: "#FF0000"
